datastore:
  host: 172.17.0.3
  port: 5432
  uid: postgres
  pwd: reporter
  db: krsdb
  schema: public

kafka:
  host: 172.16.1.141
  port: 9092
  cluster: false
  enable: false

app:
  debug: true
  host: 0.0.0.0
  port: 39001

auth:
  debug: true
  host: 0.0.0.0
  port: 39002

key:
  key_size: 4096
  jwt_key: gAAAAABdZLc584cojn5bvLQiB7cnuk_NiMhd7PGzd9RohrWxK2ITiBW9q8MpLgL1EuDqLPIk9cEzx4EHMi1btb5rstz74a3CDnk5vZwgdQdDcGW9c5cat7o=
  global_key: CR6OmG_NjJVbVYEzpHwtR1DBbHBLZ4ehUOWbFyA0Pts=
  master_key: gAAAAABdZLcJMEJ6bbYr1TS6f6SNsgf1Fk9abHglYTyqeMFCe8KeQbHyeNoF1-1QD1Rzip13ubmtucQ6B5DYnef_VpSbAzkKaPQ8kubx1kJk2mJmMRu_Zpw=
